export const INTERNATIONAL_REGIONS: Record<string, Record<string, string[]>> = {
    "Brasil": {
        "AC": ["Rio Branco", "Cruzeiro do Sul", "Sena Madureira"],
        "AL": ["Maceió", "Arapiraca", "Palmeira dos Índios"],
        "AM": ["Manaus", "Parintins", "Itacoatiara"],
        "AP": ["Macapá", "Santana", "Laranjal do Jari"],
        "BA": ["Salvador", "Feira de Santana", "Vitória da Conquista", "Camaçari"],
        "CE": ["Fortaleza", "Caucaia", "Juazeiro do Norte", "Sobral"],
        "DF": ["Brasília"],
        "ES": ["Vitória", "Vila Velha", "Serra", "Cariacica"],
        "GO": ["Goiânia", "Aparecida de Goiânia", "Anápolis", "Rio Verde"],
        "MA": ["São Luís", "Imperatriz", "Timon", "Caxias"],
        "MG": ["Belo Horizonte", "Uberlândia", "Contagem", "Juiz de Fora", "Betim"],
        "MS": ["Campo Grande", "Dourados", "Três Lagoas"],
        "MT": ["Cuiabá", "Várzea Grande", "Rondonópolis"],
        "PA": ["Belém", "Ananindeua", "Santarém", "Marabá"],
        "PB": ["João Pessoa", "Campina Grande", "Santa Rita"],
        "PE": ["Recife", "Jaboatão dos Guararapes", "Olinda", "Caruaru"],
        "PI": ["Teresina", "Parnaíba", "Picos"],
        "PR": ["Curitiba", "Londrina", "Maringá", "Ponta Grossa", "Cascavel"],
        "RJ": ["Rio de Janeiro", "São Gonçalo", "Duque de Caxias", "Nova Iguaçu"],
        "RN": ["Natal", "Mossoró", "Parnamirim"],
        "RO": ["Porto Velho", "Ji-Paraná", "Ariquemes"],
        "RR": ["Boa Vista", "Rorainópolis"],
        "RS": ["Porto Alegre", "Caxias do Sul", "Canoas", "Pelotas", "Santa Maria"],
        "SC": ["Florianópolis", "Joinville", "Blumenau", "São José", "Chapecó"],
        "SE": ["Aracaju", "Nossa Senhora do Socorro", "Lagarto"],
        "SP": ["São Paulo", "Guarulhos", "Campinas", "São Bernardo do Campo", "São José dos Campos", "Ribeirão Preto"],
        "TO": ["Palmas", "Araguaína", "Gurupi"]
    },
    "Argentina": {
        "Buenos Aires": ["CABA", "La Plata", "Mar del Plata"],
        "Córdoba": ["Córdoba Capital", "Villa Carlos Paz"],
        "Santa Fe": ["Rosario", "Santa Fe Capital"]
    },
    "United States": {
        "AL": ["Birmingham", "Montgomery", "Huntsville"],
        "AK": ["Anchorage", "Fairbanks", "Juneau"],
        "AZ": ["Phoenix", "Tucson", "Mesa"],
        "AR": ["Little Rock", "Fort Smith", "Fayetteville"],
        "CA": ["Los Angeles", "San Francisco", "San Diego", "San Jose"],
        "CO": ["Denver", "Colorado Springs", "Aurora"],
        "CT": ["Hartford", "New Haven", "Stamford"],
        "DE": ["Wilmington", "Dover"],
        "FL": ["Miami", "Jacksonville", "Tampa", "Orlando"],
        "GA": ["Atlanta", "Augusta", "Savannah"],
        "HI": ["Honolulu", "Hilo"],
        "ID": ["Boise", "Meridian", "Nampa"],
        "IL": ["Chicago", "Aurora", "Springfield"],
        "IN": ["Indianapolis", "Fort Wayne", "Evansville"],
        "IA": ["Des Moines", "Cedar Rapids", "Davenport"],
        "KS": ["Wichita", "Overland Park", "Topeka"],
        "KY": ["Louisville", "Lexington", "Bowling Green"],
        "LA": ["New Orleans", "Baton Rouge", "Shreveport"],
        "ME": ["Portland", "Lewiston", "Bangor"],
        "MD": ["Baltimore", "Frederick", "Rockville"],
        "MA": ["Boston", "Worcester", "Springfield", "Cambridge"],
        "MI": ["Detroit", "Grand Rapids", "Ann Arbor"],
        "MN": ["Minneapolis", "Saint Paul", "Rochester"],
        "MS": ["Jackson", "Gulfport", "Hattiesburg"],
        "MO": ["Kansas City", "Saint Louis", "Springfield"],
        "MT": ["Billings", "Missoula", "Great Falls"],
        "NE": ["Omaha", "Lincoln", "Bellevue"],
        "NV": ["Las Vegas", "Reno", "Henderson"],
        "NH": ["Manchester", "Nashua", "Concord"],
        "NJ": ["Newark", "Jersey City", "Trenton"],
        "NM": ["Albuquerque", "Santa Fe", "Las Cruces"],
        "NY": ["New York City", "Buffalo", "Rochester", "Albany"],
        "NC": ["Charlotte", "Raleigh", "Durham", "Greensboro"],
        "ND": ["Fargo", "Bismarck", "Grand Forks"],
        "OH": ["Columbus", "Cleveland", "Cincinnati", "Toledo"],
        "OK": ["Oklahoma City", "Tulsa", "Norman"],
        "OR": ["Portland", "Salem", "Eugene"],
        "PA": ["Philadelphia", "Pittsburgh", "Harrisburg", "Allentown"],
        "RI": ["Providence", "Warwick", "Cranston"],
        "SC": ["Columbia", "Charleston", "Greenville"],
        "SD": ["Sioux Falls", "Rapid City", "Aberdeen"],
        "TN": ["Nashville", "Memphis", "Knoxville", "Chattanooga"],
        "TX": ["Houston", "Dallas", "Austin", "San Antonio", "Fort Worth"],
        "UT": ["Salt Lake City", "Provo", "West Valley City"],
        "VT": ["Burlington", "Montpelier", "Rutland"],
        "VA": ["Virginia Beach", "Richmond", "Norfolk", "Arlington"],
        "WA": ["Seattle", "Spokane", "Tacoma", "Bellevue"],
        "WV": ["Charleston", "Huntington", "Morgantown"],
        "WI": ["Milwaukee", "Madison", "Green Bay"],
        "WY": ["Cheyenne", "Casper", "Laramie"],
        "DC": ["Washington"]
    },
    "United Kingdom": {
        "England": ["London", "Manchester", "Birmingham", "Liverpool", "Leeds", "Bristol"],
        "Scotland": ["Edinburgh", "Glasgow", "Aberdeen", "Dundee"],
        "Wales": ["Cardiff", "Swansea", "Newport"],
        "Northern Ireland": ["Belfast", "Derry", "Lisburn"]
    },
    "Portugal": {
        "Lisboa": ["Lisboa", "Sintra", "Cascais"],
        "Porto": ["Porto", "Gaia", "Matosinhos"],
        "Algarve": ["Faro", "Portimão", "Albufeira"],
        "Braga": ["Braga", "Guimarães"],
        "Coimbra": ["Coimbra", "Figueira da Foz"],
        "Aveiro": ["Aveiro", "Ílhavo"],
        "Setúbal": ["Setúbal", "Almada", "Seixal"],
        "Leiria": ["Leiria", "Caldas da Rainha"]
    },
    "Germany": {
        "Bayern": ["Munich", "Nuremberg", "Augsburg"],
        "Nordrhein-Westfalen": ["Cologne", "Düsseldorf", "Dortmund", "Essen"],
        "Baden-Württemberg": ["Stuttgart", "Mannheim", "Karlsruhe"],
        "Hessen": ["Frankfurt", "Wiesbaden", "Kassel"],
        "Berlin": ["Berlin"],
        "Hamburg": ["Hamburg"],
        "Niedersachsen": ["Hanover", "Braunschweig", "Oldenburg"],
        "Sachsen": ["Dresden", "Leipzig", "Chemnitz"]
    },
    "France": {
        "Île-de-France": ["Paris", "Versailles", "Boulogne-Billancourt"],
        "Provence-Alpes-Côte d'Azur": ["Marseille", "Nice", "Toulon"],
        "Auvergne-Rhône-Alpes": ["Lyon", "Grenoble", "Saint-Étienne"],
        "Nouvelle-Aquitaine": ["Bordeaux", "Limoges"],
        "Occitanie": ["Toulouse", "Montpellier"],
        "Hauts-de-France": ["Lille", "Amiens"]
    },
    "Spain": {
        "Madrid": ["Madrid", "Alcalá de Henares", "Getafe"],
        "Cataluña": ["Barcelona", "Tarragona", "Girona"],
        "Andalucía": ["Sevilla", "Málaga", "Granada", "Córdoba"],
        "País Vasco": ["Bilbao", "San Sebastián", "Vitoria"],
        "Valencia": ["Valencia", "Alicante"],
        "Galicia": ["A Coruña", "Vigo", "Santiago de Compostela"]
    },
    "Canada": {
        "Ontario": ["Toronto", "Ottawa", "Mississauga", "Hamilton"],
        "Quebec": ["Montreal", "Quebec City", "Laval"],
        "British Columbia": ["Vancouver", "Victoria", "Surrey"],
        "Alberta": ["Calgary", "Edmonton", "Red Deer"],
        "Manitoba": ["Winnipeg", "Brandon"],
        "Saskatchewan": ["Saskatoon", "Regina"],
        "Nova Scotia": ["Halifax", "Sydney"],
        "New Brunswick": ["Moncton", "Saint John", "Fredericton"]
    },
    "Mexico": {
        "CDMX": ["Mexico City"],
        "Jalisco": ["Guadalajara", "Zapopan", "Tlaquepaque"],
        "Nuevo León": ["Monterrey", "San Pedro Garza García", "Apodaca"],
        "Quintana Roo": ["Cancún", "Playa del Carmen", "Chetumal"],
        "Estado de México": ["Toluca", "Ecatepec", "Naucalpan"],
        "Puebla": ["Puebla", "Tehuacán"],
        "Guanajuato": ["León", "Guanajuato", "Irapuato"]
    },
    "UAE": {
        "Abu Dhabi": ["Abu Dhabi", "Al Ain"],
        "Dubai": ["Dubai"],
        "Sharjah": ["Sharjah"],
        "Ajman": ["Ajman"],
        "Ras Al Khaimah": ["Ras Al Khaimah"]
    },
    "Australia": {
        "NSW": ["Sydney", "Newcastle", "Wollongong"],
        "Victoria": ["Melbourne", "Geelong", "Ballarat"],
        "Queensland": ["Brisbane", "Gold Coast", "Cairns"],
        "WA": ["Perth", "Fremantle", "Bunbury"],
        "SA": ["Adelaide", "Mount Gambier"],
        "Tasmania": ["Hobart", "Launceston"],
        "ACT": ["Canberra"],
        "NT": ["Darwin", "Alice Springs"]
    }
};

export const BRAZIL_REGIONS = INTERNATIONAL_REGIONS["Brasil"];
